# Generated by Django 5.0.6 on 2024-06-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(max_length=100)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField()),
                ('modele', models.CharField(choices=[('PM', 'Petit Modèle'), ('GM', 'Grand Modèle')], max_length=2)),
                ('categorie', models.CharField(choices=[('AL', 'Alcoolisé'), ('NA', 'Non Alcoolisé')], max_length=2)),
            ],
        ),
    ]
