# Generated by Django 5.0.6 on 2024-06-23 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntreeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateField()),
                ('numero_de_commande_base', models.PositiveIntegerField(help_text='Entrez le numéro de commande de base')),
                ('numero_de_commande', models.CharField(blank=True, max_length=20, unique=True)),
                ('quantite', models.PositiveIntegerField()),
                ('cout_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nom_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.article')),
            ],
        ),
    ]
