# Generated by Django 5.0.6 on 2024-06-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_sortiestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortiestock',
            name='date_vente',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sortiestock',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=3, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
