# Generated by Django 5.0.6 on 2024-06-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0004_alter_sortiestock_date_vente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortiestock',
            name='date_vente',
            field=models.DateField(),
        ),
    ]
